### PR TITLE
Update README to include build from source commands

### PR DESCRIPTION
**Pull request by ldimaggi**

### CODE REVIEW

**Comment by ldimaggi** [comment]
@akashshinde 
@bamachrn

**Comment by akashshinde** [comment]
@ldimaggi Can you try enabling GO111MODULE=on and then try building using `make` once ?
because I think that should work now

**Comment by ldimaggi** [comment]
No luck - this is failing now:

make
GOBIN=/home/ldimaggi/local/redhat_git/go_path/src/helm.sh/helm/bin go install  -tags '' -ldflags '-w -s -X k8s.io/helm/pkg/version.GitCommit=df5ca23a418199c1b2af3abfc420f8339d0b9b8e -X k8s.io/helm/pkg/version.GitTreeState=clean' k8s.io/helm/cmd/...
go: warning: "k8s.io/helm/cmd/..." matched no packages

GO111MODULE=off make
GOBIN=/home/ldimaggi/local/redhat_git/go_path/src/helm.sh/helm/bin go install  -tags '' -ldflags '-w -s -X k8s.io/helm/pkg/version.GitCommit=df5ca23a418199c1b2af3abfc420f8339d0b9b8e -X k8s.io/helm/pkg/version.GitTreeState=clean' k8s.io/helm/cmd/...
go: warning: "k8s.io/helm/cmd/..." matched no packages

GO111MODULE=on make
GOBIN=/home/ldimaggi/local/redhat_git/go_path/src/helm.sh/helm/bin go install  -tags '' -ldflags '-w -s -X k8s.io/helm/pkg/version.GitCommit=df5ca23a418199c1b2af3abfc420f8339d0b9b8e -X k8s.io/helm/pkg/version.GitTreeState=clean' k8s.io/helm/cmd/...
go: warning: "k8s.io/helm/cmd/..." matched no packages

**Comment by ldimaggi** [comment]
GO111MODULE=on make
go build  -tags '' -ldflags '-w -s -X helm.sh/helm/internal/version.gitCommit=fba311ba2362ad629030c936b5d23aacb37bffcd -X helm.sh/helm/internal/version.gitTreeState=clean' -o /home/ldimaggi/local/redhat_git/go_path/src/helm.sh/helm/bin/helm helm.sh/helm/cmd/helm
go: finding k8s.io/apimachinery latest
go: finding golang.org/x/crypto latest
go: finding k8s.io/api latest
go: finding github.com/technosophos/moniker latest
go: finding k8s.io/utils latest
go: finding golang.org/x/time latest
go: finding github.com/asaskevich/govalidator latest
go: finding k8s.io/cli-runtime latest
go: finding github.com/rubenv/sql-migrate latest
go: finding k8s.io/apiextensions-apiserver latest
go: k8s.io/kubernetes@v1.16.2 requires
	k8s.io/api@v0.0.0: reading k8s.io/api/go.mod at revision v0.0.0: unknown revision v0.0.0
make: *** [Makefile:56: /home/ldimaggi/local/redhat_git/go_path/src/helm.sh/helm/bin/helm] Error 1

GO111MODULE=off make 
go build  -tags '' -ldflags '-w -s -X helm.sh/helm/internal/version.gitCommit=fba311ba2362ad629030c936b5d23aacb37bffcd -X helm.sh/helm/internal/version.gitTreeState=clean' -o /home/ldimaggi/local/redhat_git/go_path/src/helm.sh/helm/bin/helm helm.sh/helm/cmd/helm

**Comment by bamachrn** [comment]
Looks good. But did we check when we have GO111MODULE=off where from the dependencies getting picked up?

I mean the dep in Makefile is taking care of them, or they are getting picked up from vendor dir?

**Pull request closed without merging**
