### PR TITLE
Updated to support acceptance test suite

### PR DESCRIPTION
**Pull request by ldimaggi**

### CODE REVIEW

**Comment by sbose78** [comment]
No changes to the upstream makefile please, to avoid merge conflicts. If needed, add a new one :)

**Comment by ldimaggi** [comment]
@bamachrn Please review

**Comment by ldimaggi** [comment]
Closing in favor of - https://github.com/redhat-developer/helm/pull/12

**Comment by ldimaggi** [comment]
It looks like the failures are related to CI configuration - note that this is the first pull request for the helm repo since CI was configured.

**Pull request closed without merging**
