### PR TITLE
Repair failing unit tests - failure caused by io.Stat return values for directory size

### PR DESCRIPTION
**Pull request by ldimaggi**
Note that with the code changes in this pull request, the full set of unit tests run cleanly in the upstream repo (in both the master and release-v3.0.0-beta.4 branches.)

### CODE REVIEW

**Comment by ldimaggi** [comment]
Closing until we get the relationship to the upstream repo clear.

**Comment by sbose78** [comment]
Thanks, are these changes present in upstream helm?

**Comment by ldimaggi** [comment]
> Thanks, are these changes present in upstream helm?

Not yet - this PR will do that - apart from this - the unit tests run cleanly in master upstream.

**Comment by sbose78** [comment]
In that case, let's open them upstream directly to get their review.

**Comment by sbose78** [comment]
( keep the PR here as well of course )

**Comment by ldimaggi** [comment]
> In that case, let's open them upstream directly to get their review.

+1!

**Comment by ldimaggi** [comment]
The tests are failing, and will continue to fail until the tests are changed, due to environmental differences between running the tests locally and running the tests in OpenShift CI. Some of the differences are due to username differences (unknown userid 1379810000) and OpenShift project names.

**Comment by pmacik** [comment]
> The tests are failing, and will continue to fail until the tests are changed, due to environmental differences between running the tests locally and running the tests in OpenShift CI. Some of the differences are due to username differences (unknown userid 1379810000) and OpenShift project names.

@ldimaggi I'm working on fixing the OpenShift CI issues and am using this PR to check them ;)

**Comment by pmacik** [comment]
> > The tests are failing, and will continue to fail until the tests are changed, due to environmental differences between running the tests locally and running the tests in OpenShift CI. Some of the differences are due to username differences (unknown userid 1379810000) and OpenShift project names.
> 
> @ldimaggi I'm working on fixing the OpenShift CI issues and am using this PR to check them ;)

@ldimaggi FYI, I fixed the "unknown userid" issue via:

- [#27](https://github.com/redhat-developer/helm/pull/27)[/files#diff-5837afac993add809675163c027655cdR36](https://github.com/redhat-developer/helm/pull/27/files#diff-5837afac993add809675163c027655cdR36)
- https://github.com/redhat-developer/helm/pull/28

**Comment by pmacik** [comment]
@ldimaggi Is there any upstream PR for your fixes to unit tests?

**Comment by ldimaggi** [comment]
> @ldimaggi Is there any upstream PR for your fixes to unit tests?

Not yet - please feel free to create one - thx!

**Comment by pmacik** [comment]
> @ldimaggi I'm working on fixing the OpenShift CI issues and am using this PR to check them ;)
The `unknown userid` issue is fixed by https://github.com/helm/helm/pull/7147

**Comment by pmacik** [comment]
> > @ldimaggi Is there any upstream PR for your fixes to unit tests?
> 
> Not yet - please feel free to create one - thx!

Done https://github.com/helm/helm/pull/7189

**Review by sbose78 — APPROVED** [review]

**Pull request merged**
