### PR TITLE
Sync latest upstream master

### PR DESCRIPTION
**Pull request by akashshinde**

### CODE REVIEW

**Comment by pmacik** [comment]
@akashshinde Something isn't right here see the linter output:

```shell
$ make test-style
GO111MODULE=on golangci-lint run
WARN [runner] Can't run linter goanalysis_metalinter: dupl: analysis skipped: errors in package: [/home/pmacik/.go/src/github.com/redhat-developer/helm/cmd/helm/repo_remove_test.go:102:20: cannot initialize 3 variables with 2 values /home/pmacik/.go/src/github.com/redhat-developer/helm/cmd/helm/repo_remove_test.go:107:17: Home not declared by package helmpath /home/pmacik/.go/src/github.com/redhat-developer/helm/cmd/helm/repo_remove_test.go:114:12: undeclared name: ensureTestHome /home/pmacik/.go/src/github.com/redhat-developer/helm/cmd/helm/repo_remove_test.go:118:11: settings.Home undefined (type *cli.EnvSettings has no field or method Home) /home/pmacik/.go/src/github.com/redhat-developer/helm/cmd/helm/repo_remove_test.go:120:13: undeclared name: testName /home/pmacik/.go/src/github.com/redhat-developer/helm/cmd/helm/repo_remove_test.go:121:13: undeclared name: testName /home/pmacik/.go/src/github.com/redhat-developer/helm/cmd/helm/repo_remove_test.go:123:12: undeclared name: addRepository /home/pmacik/.go/src/github.com/redhat-developer/helm/cmd/helm/repo_remove_test.go:126:12: undeclared name: addRepository /home/pmacik/.go/src/github.com/redhat-developer/helm/cmd/helm/repo_remove_test.go:144:17: LoadRepositoriesFile not declared by package repo] 
WARN [runner] Can't run linter unused: buildssa: analysis skipped: errors in package: [/home/pmacik/.go/src/github.com/redhat-developer/helm/cmd/helm/installer/init.go:139:13: undeclared name: createLink] 
```

**Comment by pmacik** [comment]
@akashshinde:
we (@ldimaggi and me) are investigating a way to sync our downstream repo to upstream regularly (or on-demand) using an automated script like [this one](https://github.com/openshift/tektoncd-cli/blob/master/openshift/release/update-to-head.sh), which is used by various projects within the openshift family.

**Comment by ldimaggi** [comment]
Something isn't right in the  akashshinde:sync_master branch - in this branch the unit tests are failing with errors consistent with our downstream master branch:

```
make build

GO111MODULE=on go build  -tags '' -ldflags '-w -s -X helm.sh/helm/v3/internal/version.gitCommit=164aadf13710cb9b333f25a659d3e2121670a29b -X helm.sh/helm/v3/internal/version.gitTreeState=clean' -o /home/ldimaggi/local/redhat_git/go_path/src/k8s.io/akash/helm/bin/helm ./cmd/helm

make test-unit

==> Running unit tests <==
GO111MODULE=on go test  -run . ./... 
# helm.sh/helm/v3/cmd/helm [helm.sh/helm/v3/cmd/helm.test]
cmd/helm/repo_remove_test.go:102:17: assignment mismatch: 3 variables but repotest.NewTempServer returns 2 values
cmd/helm/repo_remove_test.go:107:8: undefined: helmpath.Home
cmd/helm/repo_remove_test.go:114:12: undefined: ensureTestHome
cmd/helm/repo_remove_test.go:118:10: settings.Home undefined (type *cli.EnvSettings has no field or method Home)
cmd/helm/repo_remove_test.go:120:13: undefined: testName
cmd/helm/repo_remove_test.go:121:13: undefined: testName
cmd/helm/repo_remove_test.go:123:12: undefined: addRepository
cmd/helm/repo_remove_test.go:126:12: undefined: addRepository
cmd/helm/repo_remove_test.go:144:12: undefined: repo.LoadRepositoriesFile
# helm.sh/helm/v3/cmd/helm/installer [helm.sh/helm/v3/cmd/helm/installer.test]
cmd/helm/installer/init.go:139:13: undefined: createLink
FAIL	helm.sh/helm/v3/cmd/helm [build failed]
FAIL	helm.sh/helm/v3/cmd/helm/installer [build failed]
ok  	helm.sh/helm/v3/cmd/helm/require	0.017s
ok  	helm.sh/helm/v3/cmd/helm/search	0.103s
# helm.sh/helm/v3/pkg/chartutil [helm.sh/helm/v3/pkg/chartutil.test]
pkg/chartutil/capabilities_test.go:61:6: use of builtin cap not in function call
# helm.sh/helm/v3/pkg/action [helm.sh/helm/v3/pkg/action.test]
pkg/action/show_test.go:82:13: undefined: tempHelmHome
pkg/action/show_test.go:86:13: undefined: resetEnv
pkg/action/show_test.go:92:2: undefined: settings
pkg/action/show_test.go:128:11: undefined: newInspectCmd
# helm.sh/helm/v3/pkg/lint/rules [helm.sh/helm/v3/pkg/lint/rules.test]
pkg/lint/rules/chartfile_test.go:70:9: undefined: validateChartName
ok  	helm.sh/helm/v3/internal/experimental/registry	1.452s
ok  	helm.sh/helm/v3/internal/ignore	0.011s
ok  	helm.sh/helm/v3/internal/monocular	0.034s
ok  	helm.sh/helm/v3/internal/resolver	0.066s
ok  	helm.sh/helm/v3/internal/sympath	0.027s
?   	helm.sh/helm/v3/internal/test	[no test files]
?   	helm.sh/helm/v3/internal/test/ensure	[no test files]
ok  	helm.sh/helm/v3/internal/third_party/dep/fs	0.037s
?   	helm.sh/helm/v3/internal/third_party/k8s.io/kubernetes/deployment/util	[no test files]
ok  	helm.sh/helm/v3/internal/tlsutil	0.014s
ok  	helm.sh/helm/v3/internal/urlutil	0.016s
?   	helm.sh/helm/v3/internal/version	[no test files]
FAIL	helm.sh/helm/v3/pkg/action [build failed]
ok  	helm.sh/helm/v3/pkg/chart	0.058s
ok  	helm.sh/helm/v3/pkg/chart/loader	0.098s
FAIL	helm.sh/helm/v3/pkg/chartutil [build failed]
?   	helm.sh/helm/v3/pkg/chartutil/generator	[no test files]
ok  	helm.sh/helm/v3/pkg/cli	0.105s
?   	helm.sh/helm/v3/pkg/cli/output	[no test files]
ok  	helm.sh/helm/v3/pkg/cli/values	0.114s
ok  	helm.sh/helm/v3/pkg/downloader	0.268s
ok  	helm.sh/helm/v3/pkg/engine	0.097s
ok  	helm.sh/helm/v3/pkg/gates	0.013s
ok  	helm.sh/helm/v3/pkg/getter	0.185s
ok  	helm.sh/helm/v3/pkg/helmpath	0.027s
?   	helm.sh/helm/v3/pkg/helmpath/xdg	[no test files]
# helm.sh/helm/v3/pkg/storage [helm.sh/helm/v3/pkg/storage.test]
pkg/storage/storage_test.go:306:59: undefined: release.Status_SUPERSEDED
pkg/storage/storage_test.go:307:59: undefined: release.Status_DEPLOYED
pkg/storage/storage_test.go:308:59: undefined: release.Status_FAILED
pkg/storage/storage_test.go:309:59: undefined: release.Status_FAILED
pkg/storage/storage_test.go:319:58: undefined: release.Status_FAILED
pkg/storage/storage_test.go:341:28: item.GetVersion undefined (type *release.Release has no field or method GetVersion)
pkg/storage/storage_test.go:342:64: item.GetVersion undefined (type *release.Release has no field or method GetVersion)
ok  	helm.sh/helm/v3/pkg/kube	0.046s
?   	helm.sh/helm/v3/pkg/kube/fake	[no test files]
ok  	helm.sh/helm/v3/pkg/lint	0.072s
FAIL	helm.sh/helm/v3/pkg/lint/rules [build failed]
ok  	helm.sh/helm/v3/pkg/lint/support	0.051s
?   	helm.sh/helm/v3/pkg/manifest	[no test files]
ok  	helm.sh/helm/v3/pkg/plugin	0.084s
?   	helm.sh/helm/v3/pkg/plugin/cache	[no test files]
ok  	helm.sh/helm/v3/pkg/plugin/installer	1.299s
ok  	helm.sh/helm/v3/pkg/provenance	0.381s
?   	helm.sh/helm/v3/pkg/release	[no test files]
ok  	helm.sh/helm/v3/pkg/releaseutil	0.012s
ok  	helm.sh/helm/v3/pkg/renderutil	0.053s
ok  	helm.sh/helm/v3/pkg/repo	0.260s
ok  	helm.sh/helm/v3/pkg/repo/repotest	0.040s
FAIL	helm.sh/helm/v3/pkg/storage [build failed]
ok  	helm.sh/helm/v3/pkg/storage/driver	0.026s
?   	helm.sh/helm/v3/pkg/storage/errors	[no test files]
ok  	helm.sh/helm/v3/pkg/strvals	0.035s
ok  	helm.sh/helm/v3/pkg/time	0.016s
FAIL
make: *** [Makefile:74: test-unit] Error 2

```

**Pull request closed without merging**
